# Generated by Django 2.1.7 on 2020-01-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Roles', 'verbose_name_plural': 'Roles'},
        ),
    ]
