# Generated by Django 2.1.7 on 2020-01-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200128_0956'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='roles',
            table=None,
        ),
    ]
